version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: belan-cars-app:1.0.0
    container_name: cars-scraper-container
    ports:
      - "3000:3000"
    restart: always