version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: belan-cars-app:1.0.0
    container_name: belan-cars-scraper-container
    ports:
      - "8080:8080"
    restart: always